-- Blackwater schema — Postgres (Supabase, Postgres 17, pgvector enabled)
-- Migrated from prototype/init_db.py (SQLite). See ../MIGRATION-NOTES.md.

CREATE EXTENSION IF NOT EXISTS vector;

DO $$ BEGIN
    CREATE TYPE entity_type AS ENUM ('npc', 'location', 'item', 'document');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE knowledge_channel AS ENUM ('witnessed', 'told_by', 'deduced', 'rumor');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE quest_template_type AS ENUM ('escalation', 'personal_crisis', 'callback', 'world_texture');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE quest_status AS ENUM (
        'generated', 'validated', 'offered', 'accepted',
        'completed', 'declined', 'failed_validation'
    );
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS entities (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type            entity_type NOT NULL,
    name            TEXT NOT NULL,
    status          TEXT NOT NULL CHECK (status IN ('alive','dead','destroyed','missing','intact')),
    location_id     INTEGER REFERENCES entities(id),
    owner_id        INTEGER REFERENCES entities(id),
    properties      TEXT,
    created_at      INTEGER NOT NULL,
    last_changed_at INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS events (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type         TEXT NOT NULL CHECK (type IN ('player_action','npc_action','world_event')),
    what         TEXT NOT NULL,
    "when"       INTEGER NOT NULL,
    location_id  INTEGER REFERENCES entities(id),
    actor_id     INTEGER REFERENCES entities(id),
    witnesses    TEXT,
    significance TEXT NOT NULL CHECK (significance IN ('high','medium','low')),
    consequences TEXT,
    embedding    vector(1536)   -- OpenAI text-embedding-3-small, over `what`. NULL until backfilled.
);

-- CREATE TABLE IF NOT EXISTS above is a no-op against an events table that
-- already exists (as it does on the live DB) — this is the actual upgrade path.
ALTER TABLE events ADD COLUMN IF NOT EXISTS embedding vector(1536);

CREATE INDEX IF NOT EXISTS events_embedding_hnsw_idx
    ON events USING hnsw (embedding vector_cosine_ops);

CREATE TABLE IF NOT EXISTS relationships (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_id         INTEGER NOT NULL REFERENCES entities(id),
    to_id           INTEGER NOT NULL REFERENCES entities(id),
    type            TEXT NOT NULL CHECK (type IN (
                        'knows','trusts','distrusts','allied','opposed',
                        'related','employed_by','owns','located_at'
                    )),
    strength        DOUBLE PRECISION CHECK (strength IS NULL OR (strength >= -1.0 AND strength <= 1.0)),
    established_at  INTEGER REFERENCES events(id),
    last_changed_at INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS player (
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    current_location_id   INTEGER REFERENCES entities(id),
    current_situation     TEXT,
    inventory             TEXT,
    visited_locations     TEXT,
    known_facts           TEXT,
    reputation_by_faction TEXT
);

CREATE TABLE IF NOT EXISTS player_choices (
    event_id      INTEGER NOT NULL REFERENCES events(id),
    significance  TEXT NOT NULL CHECK (significance IN ('high','medium','low')),
    callback_used INTEGER NOT NULL DEFAULT 0 CHECK (callback_used IN (0, 1))
);

CREATE TABLE IF NOT EXISTS npc_knowledge (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    npc_id        INTEGER NOT NULL REFERENCES entities(id),
    event_id      INTEGER NOT NULL REFERENCES events(id),
    channel       knowledge_channel NOT NULL,
    source_npc_id INTEGER REFERENCES entities(id),
    confidence    DOUBLE PRECISION NOT NULL CHECK (confidence >= 0.0 AND confidence <= 1.0),
    learned_at    INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS npc_beliefs (
    id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    npc_id                 INTEGER NOT NULL REFERENCES entities(id),
    belief_text            TEXT NOT NULL,
    confidence             DOUBLE PRECISION NOT NULL CHECK (confidence >= 0.0 AND confidence <= 1.0),
    contradicting_event_id INTEGER REFERENCES events(id),
    formed_at              INTEGER NOT NULL,
    UNIQUE (npc_id, belief_text)
);

-- CREATE TABLE IF NOT EXISTS above is a no-op against a npc_beliefs table
-- that already exists (as it does on the live DB) — this is the actual
-- upgrade path. Needed so beliefs.py can upsert via ON CONFLICT instead of
-- deciding for itself whether a row already exists.
DO $$ BEGIN
    ALTER TABLE npc_beliefs ADD CONSTRAINT npc_beliefs_npc_id_belief_text_key UNIQUE (npc_id, belief_text);
EXCEPTION
    WHEN duplicate_table THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS quests (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    npc_id              INTEGER NOT NULL REFERENCES entities(id),
    template_type       quest_template_type NOT NULL,
    status              quest_status NOT NULL,
    generated_text      TEXT,
    referenced_event_id INTEGER REFERENCES events(id),
    created_at          INTEGER NOT NULL,
    validation_log      TEXT
);
